# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='org_tag',
            field=models.CharField(default='\u77e5\u540d\u9662\u6821', max_length=10, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
