# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tellyou',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bb2\u5e08\u63d0\u9192'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
