# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170913_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('fmale', '\u5973')], default='female', max_length=6),
        ),
    ]
